USE [master]
GO
/****** Object:  Database [innovacorp]    Script Date: 9/2/2025 16:02:47 ******/
CREATE DATABASE [innovacorp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'innovacorp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\innovacorp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'innovacorp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\innovacorp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [innovacorp] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [innovacorp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [innovacorp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [innovacorp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [innovacorp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [innovacorp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [innovacorp] SET ARITHABORT OFF 
GO
ALTER DATABASE [innovacorp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [innovacorp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [innovacorp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [innovacorp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [innovacorp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [innovacorp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [innovacorp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [innovacorp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [innovacorp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [innovacorp] SET  ENABLE_BROKER 
GO
ALTER DATABASE [innovacorp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [innovacorp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [innovacorp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [innovacorp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [innovacorp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [innovacorp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [innovacorp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [innovacorp] SET RECOVERY FULL 
GO
ALTER DATABASE [innovacorp] SET  MULTI_USER 
GO
ALTER DATABASE [innovacorp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [innovacorp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [innovacorp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [innovacorp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [innovacorp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [innovacorp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'innovacorp', N'ON'
GO
ALTER DATABASE [innovacorp] SET QUERY_STORE = ON
GO
ALTER DATABASE [innovacorp] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [innovacorp]
GO
/****** Object:  Table [dbo].[Inventario]    Script Date: 9/2/2025 16:02:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Producto] [nvarchar](100) NOT NULL,
	[Cantidad] [int] NOT NULL,
	[FechaActualizacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedidos]    Script Date: 9/2/2025 16:02:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedidos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Producto] [nvarchar](100) NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Fecha] [datetime] NULL,
	[Estado] [nvarchar](20) NOT NULL,
	[FechaEntrega] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reportes]    Script Date: 9/2/2025 16:02:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reportes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [nvarchar](100) NOT NULL,
	[Detalle] [nvarchar](255) NOT NULL,
	[Fecha] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Inventario] ADD  DEFAULT (getdate()) FOR [FechaActualizacion]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT (getdate()) FOR [Fecha]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT ('pendiente') FOR [Estado]
GO
ALTER TABLE [dbo].[Reportes] ADD  DEFAULT (getdate()) FOR [Fecha]
GO
USE [master]
GO
ALTER DATABASE [innovacorp] SET  READ_WRITE 
GO
